### ISSUE TITLE
Not sure how to install

### ISSUE THREAD

**Issue by Robotghost718** [dwmorrin/py-inline-html#1]
I keep getting the error on calling make in your gas-eco project, but can't find a way to fulfill the requirement for the inline script either with installing via pip or other ways. Can you enlighten me?

**Comment by dwmorrin** [comment]
Hi! I just updated gas-eco recently to remove this requirement.  Try updating gas-eco and see if the replacement makes sense (I switched to using a node.js HTML parser).

To answer your question:
The old gas-eco Makefile is looking for a command called `inline`, so I copy the `inline.py` file from here into ~/bin (or some directory in your $PATH), change the name to just `inline` and run `chmod +x ~/bin/inline` so it is executable.

I apologize for the confusion. The update to use node.js instead of python eliminates this entirely.  You just need to run `npm install` in the updated gas-eco to install the HTML parser.

**Comment by Robotghost718** [comment]
No need to apologize! Thank you for the quick response, I had just noticed I had forked your old master but had  been using the most recent commit for reference. Thanks again for your detailed answer and your work, it's exactly what I've been looking for! I'll mark this as resolved on my end!
